import './globals.css'
import type { Metadata } from 'next'
import { Gabarito } from 'next/font/google'

const inter = Gabarito({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' data-theme='light'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
